### ISSUE TITLE
Issue with axis sizes

### ISSUE THREAD

**Issue by kruftindustries** [KalebKE/ME7Tuner#13]
Axis dimensions are not used when loading tables? (not sure if bug or feature request)

The old code was pretty straight-forward to modify for my ME7.5 audi for example but it's a bit more complicated now.

Examples:
KFMIOP selection does not seem to work with my xdf
KFZW/OP tables appear weird once loaded
there might have been an issue with DIMX and with KSD/E but wasn't able to determine what exactly. 

It looks like there is error/exception handling with message pop-up that is disabled? Is there a way to enable that? or is that part of some other framework that is unrelated?

If certain tables are selected application will not start before deleting registry entries (Windows OS) in `HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Prefs` and it's difficult to troubleshoot what is happening

Also, thank you! This refresh is really nice, functionality is impressive! Let me know if I can help, maybe I could implement MLOFS for closed loop fueling and options for open loop fueling that would apply to wideband ecu's (without zeitronics)?

**Comment by kruftindustries** [comment]
I think MLHFM selected will cause the crash on open if selected.
[files.zip](https://github.com/KalebKE/ME7Tuner/files/8199704/files.zip)

**Comment by KalebKE** [comment]
Hi,

I have pushed a patch on the v1.0.1 release. Please give it a try.

**Comment by kruftindustries** [comment]
Able to select everything now. Swapped axis in KFZWOP and it loads correctly. I'm about to test KFMIRL/IOP as generated, looks a lot better than what I had!

**Comment by kruftindustries** [comment]
KFZW does not seem to be interpolating/extrapolating. Might need to restart and try again.

**Comment by kruftindustries** [comment]
IOP/IRL gave really smooth and consistent torque. KFZW is still not interpolating, the output table is showing the bin contents on opening the tab and changing the input table or axis input does not seem to update the output table

**Comment by kruftindustries** [comment]
Could you please double check the , the KFVPDKSD/E "write bin" button isn't supposed to write the output table to every file in the directory?

**Comment by KalebKE** [comment]
KFZW issue has been resolved in https://github.com/KalebKE/ME7Tuner/releases/tag/v1.0.2

A bin file will stay loaded until you explicitly change it. The calculations from parsing a file are only valid for that parse and will be lost when the application is closed unless you write the changes to the bin.
